---
# handlers file for slacko

- name: "enable mongodb"
  systemd:
    name: mongodb
    state: started
    enabled: yes

- name: "Start slacko-api.service"
  systemd:
    name: slacko-api.service
    state: started
    enabled: yes